variables
Oleksandr26/hellen-project pull request #7
Opened 2022-06-04 17:04 UTC by vzotova85

- background colors added
- text colors added

2022-06-04 18:04 UTC, Oleksandr26 requested changes

2022-06-04 18:04 UTC, Oleksandr26 commented on src/sass/_variables.scss
> +$bg-color-wtihe: #FFFFFF;
напиши пожалуйста white просто что бы не путались

2022-06-04 18:04 UTC, Oleksandr26 commented on src/sass/_variables.scss
> +$text-color-wtihe: #FFFFFF;
напиши пожалуйста white просто что бы не путались

2022-06-05 10:09 UTC, vzotova85 reviewed
done

2022-06-05 11:04 UTC, Oleksandr26 approved these changes

2022-06-05 11:04 UTC, merged